typography_spectrum: 0.8250840371474624
content_rating:
  adult: false
color:
  brandStrength: 0.34434866602532566
  lightness: 0.7690227527637035
  saturation: 0.38923389790579677
  rhythmicContrast: 0.869654736481607
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
layout_spectrum: 0.9952141782268882
author:
  name: ''
  email: ''
name: Nicole Perez Art
navigation:
  - id: 'https://www.facebook.com/nicoleperezart/'
    url: 'https://www.facebook.com/nicoleperezart/'
    name: Facebook
    type: external
  - id: 'https://www.etsy.com/shop/NicolePerezArt'
    url: 'https://www.etsy.com/shop/NicolePerezArt'
    name: Etsy
    type: external
  - id: 'https://www.instagram.com/nicoleperezart/'
    url: 'https://www.instagram.com/nicoleperezart/'
    name: Instagram
    type: external
