typography_spectrum: 0.6498027094639838
content_rating:
  adult: false
color:
  brandStrength: 0.8728553289547563
  lightness: 0.6374120081309229
  saturation: 0.6594134196639061
  rhythmicContrast: 0.3118686054367572
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
layout_spectrum: 0.21595410234294832
author:
  name: ''
  email: ''
name: Nicole Perez Art
navigation:
  - id: 'https://www.facebook.com/nicoleperezart/'
    url: 'https://www.facebook.com/nicoleperezart/'
    name: Facebook
    type: external
  - id: 'https://www.etsy.com/shop/NicolePerezArt'
    url: 'https://www.etsy.com/shop/NicolePerezArt'
    name: Etsy
    type: external
  - id: 'https://www.instagram.com/nicoleperezart/'
    url: 'https://www.instagram.com/nicoleperezart/'
    name: Instagram
    type: external
